# Generated by Django 2.2.1 on 2019-05-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regist',
            new_name='Registration',
        ),
    ]
