# Generated by Django 2.2.1 on 2019-05-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190528_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='who',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='day',
            field=models.CharField(default='なし', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='wtr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
