# Generated by Django 2.2.1 on 2019-06-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='TF',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
