# Generated by Django 2.2.1 on 2019-06-17 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_search_tf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordID',
            fields=[
                ('discord_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Discord_ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
