# Generated by Django 2.2.1 on 2019-06-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_discordid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordID',
        ),
    ]
